#!/bin/bash

# Config for Cerealbox scripts

# Variables for printrbot scripts
BAR_STORED=176
BAR_DEPLOYED=120
BAR_FORWARD=060
CB_DIR=/home/pi/cerealbox
CB_DOTDIR=/home/pi/.cerealbox

# Source API keys
. $CB_DOTDIR apis.sh

# Dimensions allowed for scanning the part off the build plate
X_MIN=0
X_MAX=130
Y_MIN=5
Y_MAX=145
Z_MIN=14
Z_MAX=145
X_STEP=25
Z_STEP=-4

# Toggles
RQ_ENABLED=true
POP_ENABLED=false
PUSH_ENABLED=false
TIMEOUT_ENABLED=false

# Time for build plate to cool
COOLDOWN=30

# Set up resty
. $CB_DIR/resty

