#!/bin/bash

# Config for Cerealbox scripts

# Set local directory variable
if [ ! -d "$LOCAL_DIR" ]; then
	LOCAL_DIR="$( dirname "$( readlink -f "$0" )" )"
fi

# Check if the dirs are sourced
if [ ! -d "$UTIL_DIR" ]; then
	. "$LOCAL_DIR/dirs"
fi

AVR_DEV=/dev/ttyAMA0

# Variables for printrbot scripts
BAR_STORED=172
BAR_DEPLOYED=120
BAR_FORWARD=035
BAR_PUSH=080

# Declare that the dotdir is just in the same parent directory
CB_DOTDIR=$CB_DIR/../.cerealbot

# Source API keys from somewhere not sent to github
. "$CB_DOTDIR/apis"

# Dimensions allowed for scanning the part off the build plate
X_MIN=0
X_MAX=100
Y_MIN=5
Y_MAX=145
Z_MIN=16
Z_MAX=145
Y_SWING=-30 # Distance to move Y is bar needs to be swung
Z_SWING=25 # If Z below this, then move Y before swinging bar
X_STEP=25
Z_STEP=4

# Toggles
SERIAL_ENABLED=true
RQ_ENABLED=true
POP_ENABLED=false
PUSH_ENABLED=false
TIMEOUT_ENABLED=true

# Time for build plate to cool
COOLDOWN=30

# Number of times to cycle hotbed
POP_CYCLES=6

# Set printer busy lockfile
LOCKFILE=/tmp/cb_busy.lck

# Set up resty
. "$UTIL_DIR/resty"

