#!/bin/bash

# Collection of helper functions for CerealBot

# Set local directory variable
if [ ! -d "$LOCAL_DIR" ]; then
	LOCAL_DIR="$( dirname "$( readlink -f "$0" )" )"
fi

# Check if the dirs are sourced
if [ ! -d "$UTIL_DIR" ]; then
	. "$LOCAL_DIR/dirs"
fi

. $UTIL_DIR/config

# Accept string input and write it to irc channels
function rq_msg {
	$UTIL_DIR/send_rq_msg.sh "$@"
}

# function to print to std, rq, and logfile
function write_msg {
	$UTIL_DIR/write_msg.sh "$@"
}

# Forward arguments to servoctl.sh
function servoctl {
	$UTIL_DIR/set_servo.sh "$@"
}

# Forward arguments to fanctl.sh
function fanctl {
	$UTIL_DIR/set_fan.sh "$@"
}

# Forward arguments to printr_status.sh
function printr_status {
	$UTIL_DIR/get_cb_status.sh "$@"
}

# Forward arguments to printr_cmd.sh
function printr_cmd {
	$UTIL_DIR/send_cb_cmd.sh "$@"
}


















