#! /bin/sh

### BEGIN INIT INFO
# Provides:          envmon
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Fab Lab environment graphing
# Description:       more foo for your bars
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting envmon "
    
    # example 1 - system service
    # /usr/bin/foobar --config /etc/foo.conf start

    /home/pi/cerealbox/envmon/start_server.sh >> /dev/null &

    # example 2 - run script as user
    # su --login mkaz --command "/home/mkaz/bin/my-script --cmd-args"
    
    ;;
  stop)
    echo "Stopping foobar"

    kill $(cat /tmp/envmon_server.pid) 

    # example 1
    # /usr/bin/foobar --config /etc/foo.conf stop

    ;;
  *)
    echo "Usage: /etc/init.d/foobar {start|stop}"
    exit 1
    ;;
esac

exit 0
