ARDUINO_DIR = /usr/share/arduino
ARDMK_DIR = /usr/share/arduino
AVR_TOOLS_DIR = /usr
ARDUINO_CORE_PATH = /usr/share/arduino/hardware/arduino/avr/cores/arduino
BOARDS_TXT = /usr/share/arduino/hardware/arduino/avr/boards.txt
ARDUINO_VAR_PATH = /usr/share/arduino/hardware/arduino/avr/variants
BOOTLOADER_PARENT = /usr/share/arduino/hardware/arduino/avr/bootloaders

TARGET       = printr_avr
ARDUINO_LIBS = Servo amt1001

#BOARD_TAG    = atmega328
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyAMA0

include /usr/share/arduino/Arduino.mk





